url: https://strongstartsforsuccess.org
baseurl: /

# Site settings
title: Strong Starts for Success
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
background_image: hero-bg-2.jpg
mission: Provide safe, high-quality, affordable, community-based, holistic education for Liberia's youngest children.

# Team names, titles and social links
people:
- name: Hailey Breitenfeld
  pic: hailey_breitenfeld.jpg
  position: Founder and Executive Director
  description: "Hailey holds a Master of Arts in International Education from New York University and a Bachelor of Arts in Psychology and a minor in Applied Developmental Psychology from University of California, Los Angeles (UCLA). She fell in love with West Africa in 2010 while studying abroad in Ghana and volunteering at Ghanaian public schools as she earned her bachelor’s degree from UCLA. Hailey has traveled to work in the education system in many African countries, including Ghana, Ethiopia, Tanzania, Kenya, Sierra Leone, and Liberia. Through her work and travels, she has enhanced her skills as an International Early Childhood Care and Education Professional by training teachers, developing curricula, teaching students, collecting and analyzing data, and co-directing a primary school. Hailey has always been drawn to the youngest children and carves out time to interact with them no matter her job description. She enjoys discovering and feeding their evident hunger for learning. The mission at Strong Starts for Success (S3) evolved from these experiences which opened the door for Hailey to pursue her passion for enabling the youngest children to have the best possible start in life. After years of learning, teaching and searching, Hailey is excited to create the first of S3’s developmentally appropriate early education centers in Harlandsville, Liberia. Now, the history of S<sup>3</sup> is just beginning, join us on the journey."
  modal-id: 1

- name: Makenna Breitenfeld
  pic: makenna_breitenfeld.jpg
  position: President
  description: "Makenna holds a Bachelor of Arts in Legal Studies from University of California, Santa Cruz and Bachelor of Science in Nursing from University of Miami. As president of the board, Makenna guides Strong Starts for Success, drawing from her experience as a consumer analyst, enterprise community manager, and registered nurse. Makenna is an avid biker, climber, outdoor enthusiast and advocate for education and knowledge sharing."
  modal-id: 2

- name: Precious Marshall
  pic: precious_marshall.jpg
  position: Secretary
  description: "Margaret P. Marshall received her Bachelor of Science degree in Information Systems with focus on Database Management from Strayer University and her master’s degree in Education specializing in Adult Education and Training from University of Phoenix. She began her professional career in banking and finance, then followed her passion to education. She has served as an Administrator for Ricks Institute in Liberia, Associate Vice President of Internal Audit and Management Control at Cuttington University College and the Vice President for Enrollment Management at Notre Dame University College of Liberia. Her skills as an educator, administrator, facilitator, trainer, mentor, and a promising poet will keep Strong Starts for Success organized and flourishing."
  modal-id: 3

- name: Ada Rousso
  pic: ada_rousso.jpg
  position: Treasurer
  description: "Ada has a JD from American University and an LLM in tax from Georgetown University. She was a senior manager with Price Waterhouse Coopers. She currently is a Director of Resource Development at Mango Tree Productions, Inc., and has been a member of the Board of Trustees at the Santa Monica Synagogue. As a member of the board of Strong Starts for Success, she hopes to use her expertise as a tax attorney to ensure that decisions regarding finances are effectively managed at their best and most productive use for the school. She loved watching her grandchildren go through their early school years and hopes to bring similar positive experiences to Strong Starts for Success."
  modal-id: 4

- name: Etmonia King-Kerpen
  pic: ettie_king.jpg
  position: Member
  description: Etmonia "Ettie" was born and raised in Liberia. She spent her career as a kindergarten teacher in international schools around the world, including in Senegal and Europe. She currently resides in the United States, but frequently travels back home to visit, advise, and train on matters relating to Early Childhood Care and Education (ECCE). Ettie can be heard excitedly telling anyone who will listen that “early childhood is my soul!” Strong Starts for Success is lucky to have a team member so passionate about the children and community we are serving.
  modal-id: 5

- name: Laurie Healy
  pic: laurie_healy.jpg
  position: Member
  description: "Laurie has a degree in Liberal Studies from Cal State University, Northridge and an Early Childhood Education Director Certificate from UCLA. She brings education, experience, passion, and creativity to Strong Starts for Success and the children of Liberia. Teaching in the classroom for 20+ years, at the preschool and kindergarten levels, allowed her to infuse a variety of learning modalities to help reach children of all learning styles; her favorite being empowering children to do something for the first time. As an Early Childhood Education director, she spearheaded the implementation of Reggio Emilio inspired learning, in addition to opening the school’s first Toddler Program. Currently, Laurie works at a summer day camp in the Los Angeles area where the focus is fun, friendship and great outdoor activities. Laurie and her husband Pat have been married for over 30 years and together have three adult children and four grandchildren. Through her grandchildren, she stays up to date with best practices in early childhood education.  Laurie is passionate and committed to all children having access to quality early education."
  modal-id: 6

- name: Marilyn Cahn
  pic: marilyn_cahn.jpg
  position: Member
  description: "Marilyn holds a Bachelor of Arts from National University in K-12 Teaching and certification for Special Education from Cal State University, Northridge. She spent her career as a special education teacher, ensuring that her students were prepared to be active and productive members of their communities. She continues to relentlessly support and promote any cause she believes in and brings that passion to the board of Strong Starts for Success. Her uncanny gift for seeking the positive in any situation adds an optimistic perspective to the organization."
  modal-id: 7

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/strongstartsforsuccess
  - title: envelope
    url: mailto:foo@bar.com
  - title: facebook
    url: https://www.facebook.com/strongstartsforsuccess

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
